const UpcomingTripsData = [
  {
    id: "BirBilling",
    TripPhoto: "/media/bir2.jpg",
    FromLocation: "Delhi",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Noida",
    TripPhoto: "/media/taj.jpg",
    FromLocation: "AGRA",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Banglore",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Banglore",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Chennai",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Chennai",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Pune",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Pune",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Nagaland",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
  {
    id: "Nagaland",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: ["Dec", "Jan", "Feb", "Mar", "Apr"],
  },
];

export default UpcomingTripsData;
