const UpcomingTripsData = [
  {
    id: "BirBilling",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Delhi",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Noida",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Noida",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Banglore",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Banglore",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Chennai",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Chennai",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Pune",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Pune",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  {
    id: "Kolkata",
    TripPhoto: "/media/manali.jpeg",
    FromLocation: "Kolkata",
    Duration: "3N/4D",
    Triptitle: "Vietnam 8 Days Trip WIth FLight",
    Dates: "14 Oct, 24 Oct, 29 Oct",
  },
  //   {
  //     id: "Nagaland",
  //     TripPhoto: "/media/manali.jpeg",
  //     FromLocation: "Kolkata",
  //     Duration: "3N/4D",
  //     Triptitle: "Vietnam 8 Days Trip WIth FLight",
  //     Dates: "14 Oct, 24 Oct, 29 Oct",
  //   },
  //   {
  //     id: "Nagaland",
  //     TripPhoto: "/media/manali.jpeg",
  //     FromLocation: "Kolkata",
  //     Duration: "3N/4D",
  //     Triptitle: "Vietnam 8 Days Trip WIth FLight",
  //     Dates: "14 Oct, 24 Oct, 29 Oct",
  //   },
];

export default UpcomingTripsData;
